services:
  deno:
    #user: ${UID}:${GID}
    build: ./docker
    image: vitereactdeno
    restart: always
    container_name: vitereactdeno
    volumes:
      - ./app/:/app
    ports:
      #- 5173:5173
      - 8000:8000
    expose:
      #- 5173
      - 8000
    tty: true
    command:
      - /bin/sh
      - -c
      #- deno task dev --host
      - deno task serve --host
